import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
	{
		_id: uuid(),
		firstName: "Adarsh",
		lastName: "Balika",
		username: "adarshbalika",
		password: "adarshBalika123",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "A very adarsh developer balika",
		profileImage:
			"https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=461&q=80",
		website: "https://adarshbalika.netlify.app/",
		followers: ["shubhamsoni", "bhaaratii", "johndoe", "janedoe"],
		following: ["shubhamsoni", "johndoe", "janedoe", "hergranger"],
	},
	{
		_id: uuid(),
		firstName: "Shubham",
		lastName: "Soni",
		username: "shubhamsoni",
		password: "shubhamsoni123",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "Loves Code, Books, Coffee, and Songs in no particular order!",
		profileImage:
			"https://images.unsplash.com/photo-1633332755192-727a05c4013d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
		website: "https://www.shubhamsoni.me/",
		followers: ["adarshbalika", "bhaaratii", "annachase", "percyblues"],
		following: ["adarshbalika", "bhaaratii", "janedoe"],
	},
	{
		_id: uuid(),
		firstName: "Bharati",
		lastName: "Subramanian",
		username: "bhaaratii",
		password: "bharati123",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "Loves Code, Books, Coffee, and Songs in no particular order!",
		profileImage:
			"https://pbs.twimg.com/profile_images/1418817136349360129/LEwV3Q71_400x400.jpg",
		website: "bharati-21.github.io",
		followers: ["shubhamsoni", "hergranger", "youknowhow"],
		following: [
			"adarshbalika",
			"shubhamsoni",
			"hergranger",
			"annachase",
			"percyblues",
		],
	},
	{
		_id: uuid(),
		firstName: "John",
		lastName: "Doe",
		username: "johndoe",
		password: "johndoe",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "Graphic Design | UI/ UX Design | Photography",
		profileImage:
			"https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
		website: "https://johndoe-portfolio.netlify.app/",
		followers: ["adarshbalika", "janedoe", "hergranger", "percyblues"],
		following: ["adarshbalika", "janedoe", "youknowwho"],
	},
	{
		_id: uuid(),
		firstName: "Jane",
		lastName: "Doe",
		username: "janedoe",
		password: "janedoe789",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "Web Developer",
		profileImage:
			"https://raw.githubusercontent.com/PhantomScript/asset-container/main/developer-portfolio/landingImg.png",
		website: "https://dev-portfolio-template.netlify.app/",
		followers: ["adarshbalika", "shubhamsoni", "johndoe", "annachase"],
		following: ["adarshbalika", "johndoe", "youknowwho"],
	},
	{
		_id: uuid(),
		firstName: "Hermione",
		lastName: "Granger",
		username: "hergranger",
		password: "granferspew",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "Web Developer",
		profileImage:
			"https://static.wikia.nocookie.net/harrypotter/images/3/34/Hermione_Granger.jpg/revision/latest?cb=20210522145306",
		website: "https://harrypotter.fandom.com/wiki/Hermione_Granger",
		followers: ["adarshbalika", "bhaaratii", "annachase", "percyblues"],
		following: ["bhaaratii", "johndoe", "annachase", "percyblues"],
	},
	{
		_id: uuid(),
		firstName: "Annabeth",
		lastName: "Chase",
		username: "annachase",
		password: "grayeyes",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "Architecht | Demigod | Daughter of Athena",
		profileImage:
			"https://static.wikia.nocookie.net/olympians/images/c/ca/Annabeth_Chase-Viria.jpg/revision/latest/scale-to-width-down/596?cb=20170220200242",
		website: "https://riordan.fandom.com/wiki/Annabeth_Chase",
		followers: ["bhaaratii", "hergranger", "percyblues", "youknowwho"],
		following: ["shubhamsoni", "janedoe", "hergranger", "percyblues"],
	},
	{
		_id: uuid(),
		firstName: "Perseus",
		lastName: "Jackson",
		username: "percyblues",
		password: "riptide",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "Demigod | Son of Poseidon | Loves Annabeth and all food blue!",
		profileImage:
			"https://static.wikia.nocookie.net/olympians/images/1/10/Percy_Jackson.jpg/revision/latest/scale-to-width-down/596?cb=20180319172727",
		website: "https://riordan.fandom.com/wiki/Percy_Jackson",
		followers: ["bhaaratii", "hergranger", "percyblues", "youknowwho"],
		following: ["shubhamsoni", "johndoe", "hergranger", "annachase"],
	},
	{
		_id: uuid(),
		firstName: "Alex",
		lastName: "Smith",
		username: "youknowwho",
		password: "emgraphics",
		createdAt: formatDate(),
		updatedAt: formatDate(),
		bio: "Passionate Graphic Designer from New York",
		profileImage:
			"https://bootstrapmade.com/demo/templates/iPortfolio/assets/img/profile-img.jpg",
		website: "https://bootstrapmade.com/demo/templates/iPortfolio/",
		followers: ["johndoe", "janedoe"],
		following: ["bhaaratii", "annachase", "percyblues"],
	},
];
